// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0x5o43ace6zV4aXVL_gLvpADs3eiKiOk',
    appId: '1:41883908141:web:0c15cc1906873400cb20a4',
    messagingSenderId: '41883908141',
    projectId: 'tunisnext-mirror',
    authDomain: 'tunisnext-mirror.firebaseapp.com',
    storageBucket: 'tunisnext-mirror.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL2UqRt6nhYFsy37T5Cz4BKwsabJluz94',
    appId: '1:41883908141:android:e9d2e66468cbbd0dcb20a4',
    messagingSenderId: '41883908141',
    projectId: 'tunisnext-mirror',
    storageBucket: 'tunisnext-mirror.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_yZ0R1hb7mfEfYRKT0CPnl0WOzin9iHI',
    appId: '1:41883908141:ios:b4e93c4507a306c1cb20a4',
    messagingSenderId: '41883908141',
    projectId: 'tunisnext-mirror',
    storageBucket: 'tunisnext-mirror.firebasestorage.app',
    iosBundleId: 'com.anonchat.anonchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_yZ0R1hb7mfEfYRKT0CPnl0WOzin9iHI',
    appId: '1:41883908141:ios:b4e93c4507a306c1cb20a4',
    messagingSenderId: '41883908141',
    projectId: 'tunisnext-mirror',
    storageBucket: 'tunisnext-mirror.firebasestorage.app',
    iosBundleId: 'com.anonchat.anonchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0x5o43ace6zV4aXVL_gLvpADs3eiKiOk',
    appId: '1:41883908141:web:99d67b79988732e1cb20a4',
    messagingSenderId: '41883908141',
    projectId: 'tunisnext-mirror',
    authDomain: 'tunisnext-mirror.firebaseapp.com',
    storageBucket: 'tunisnext-mirror.firebasestorage.app',
  );
}
